


# +
# Use the largest batchsize possible
BATCH_SIZE = 256
# BATCH_SIZE = 8
# BATCH_SIZE = 1024

# Using LARS will require some gnarly pytorch DDP rewrite or pytorch lightning etc port
# USE_LARS = True
USE_LARS = False

# Resnet output 1000 dimensional vectors
DIM = 1000

# Number of torchsynth voice params
NPARAMS = 78

# torchsynth default
RATE = 44100


# PRETRAIN_STEPS = 128
PRETRAIN_STEPS = 1024000

# PRETRAIN_STEPS_CHECKPOINT_EVERY = 10
PRETRAIN_STEPS_CHECKPOINT_EVERY = 10000
# -

# args.mlp = "8192-8192-8192"
args.mlp = f"1024-1024-{DIM}"
args.batch_size = BATCH_SIZE

args.sim_coeff = 25.0
args.std_coeff = 25.0
args.cov_coeff = 1.0
# args.sim_coeff = 1.0
# args.std_coeff = 0.0
# args.cov_coeff = 0.0
args.wd = 1e-6

sample_rate = 44100


n_fft = 1024
win_length = None
hop_length = 512
n_mels = 128
