# Use the largest batchsize possible
#batch_size: 8
batch_size: 256

num_workers: 1

torchsynth:
    reproducible: False
    buffer_size_seconds: 4.0
    # torchsynth default
    rate: 44100

vicreg:
#    continue_from: "vicreg.pth"
    continue_from: null

    # Using LARS will require some gnarly pytorch DDP rewrite or pytorch lightning etc port
    use_lars: False
    #use_lars: True

#    nsteps: 128
    nsteps: 1024000

#    checkpoint_every_nsteps: 10
    checkpoint_every_nsteps: 10000

    mlp: "1024-1024-%d"

    sim_coeff: 25.0
    std_coeff: 25.0
    cov_coeff: 1.0
    weight_decy: 1e-6

    pretrained_vision_model: True

mel:
    n_fft: 1024
    win_length: null
    hop_length: 512
    center: True
    pad_mode: "reflect"
    power: 2.0
    norm: "slaney"
    onesided: True
    n_mels: 128
    mel_scale: "htk"
    

# torchvision outputs 1000 dimensional vectors
dim: 1000

# Number of torchsynth voice params
nparams: 78
