#precision: 16
# Try this to avoid NaN too late through
#precision: bf16
accelerator: "gpu"
#accelerator: "cpu"
#devices: 2
devices: 1
strategy: "ddp"

num_batches: 50000000

num_workers: 1

log: wand
#log: null

# Hidden and representation dimension
#dim: 512
#dim: 256
dim: 1024
# Embedding (projection) dimension.
# According to VICReg paper, bigger is better.
# This leads to lower representation loss.
embeddim: 8192

# Number of torchsynth voice params
nparams: 78

seed: 42

ntest_batches: 1

defaults:
  - vicreg: full
  - audio_to_params: small

torchsynth:
    reproducible: False
    buffer_size_seconds: 4.0
    # torchsynth default
    rate: 44100

param_embed:
    # Used in heareval
    hidden_norm: nn.BatchNorm1d
    #hidden_norm: nn.Identity
    # Used in heareval
    dropout: 0.0


#mel:
#    n_fft: 1024
#    win_length: null
#    hop_length: 512
#    center: True
#    pad_mode: "reflect"
#    power: 2.0
#    norm: "slaney"
#    onesided: True
#    n_mels: 128
#    mel_scale: "htk"
